### ISSUE TITLE
Missing Files on Initial Gradle Build of ver 1.5.2

### ISSUE THREAD

**Issue by TheCodeMantra** [jjhesk/BringItBackAdvanceSlidingMenu#1]
Hi jjhesk - I have loaded your build ver 1.5.2 into Android Studio 141.2024585. The Gradle build went fine, with the exception of 7 errors as shown below. Can you please advise where the missing files can be found? Thanks in advance. Regards, TCM

C:\Users\TCM\Documents\AndroidStudioProjects\BringItBackAdvanceSlidingMenu-1.5.2\AdvancedSlidingMenu\demoslidemenu\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\7.5.0\res\drawable\common_signin_btn_icon_dark.xml
Error:(10, 28) No resource found that matches the given name (at 'drawable' with value '@drawable/common_signin_btn_icon_disabled_focus_dark').

C:\Users\TCM\Documents\AndroidStudioProjects\BringItBackAdvanceSlidingMenu-1.5.2\AdvancedSlidingMenu\demoslidemenu\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\7.5.0\res\drawable\common_signin_btn_icon_light.xml
Error:(10, 28) No resource found that matches the given name (at 'drawable' with value '@drawable/common_signin_btn_icon_disabled_focus_light').
Error:(16, 28) No resource found that matches the given name (at 'drawable' with value '@drawable/common_signin_btn_icon_disabled_light').

C:\Users\TCM\Documents\AndroidStudioProjects\BringItBackAdvanceSlidingMenu-1.5.2\AdvancedSlidingMenu\demoslidemenu\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\7.5.0\res\drawable\common_signin_btn_text_dark.xml
Error:(10, 28) No resource found that matches the given name (at 'drawable' with value '@drawable/common_signin_btn_text_disabled_focus_dark').

C:\Users\TCM\Documents\AndroidStudioProjects\BringItBackAdvanceSlidingMenu-1.5.2\AdvancedSlidingMenu\demoslidemenu\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\7.5.0\res\drawable\common_signin_btn_text_light.xml
Error:(10, 28) No resource found that matches the given name (at 'drawable' with value '@drawable/common_signin_btn_text_disabled_focus_light').
Error:(16, 28) No resource found that matches the given name (at 'drawable' with value '@drawable/common_signin_btn_text_disabled_light').
Error:Execution failed for task ':demoslidemenu:processDebugResources'.

> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Users\TCM\AppData\Local\Android\sdk\build-tools\22.0.1\aapt.exe'' finished with non-zero exit value 1

**Comment by jjhesk** [comment]
I think the setup for mine went normal. 
my build script is 

``` gradle

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.2.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

```

with the default gradle compile script mentioned from the readme file and the wiki.
