### ISSUE TITLE
Not handling phones without navigation bar

### ISSUE THREAD

**Issue by fbcbl** [jjhesk/BringItBackAdvanceSlidingMenu#12]
How can I fix this?

**Comment by jjhesk** [comment]
You can give it a try in [the core code](https://github.com/jjhesk/BringItBackAdvanceSlidingMenu/blob/V1/AdvancedSlidingMenu/slidingmenulib/src/main/java/com/hkm/slidingmenulib/gestured/SlidingMenu.java#L1065-L1088)

**Comment by jjhesk** [comment]
fixed. @fabiocarballo
