### ISSUE TITLE
Gradle project sync failed.  Error says 'Failed to Resolve...'

### ISSUE THREAD

**Issue by sepranagw** [jjhesk/BringItBackAdvanceSlidingMenu#14]
Here is the build.gradle (module) : 

apply plugin: 'com.android.application'
repositories { maven {  url "https://jitpack.io"  }}
android {
    compileSdkVersion 21
    buildToolsVersion "21.1.2"
    defaultConfig {
        applicationId "xyzapplicationsolutions.com.myapp"
        minSdkVersion 14
        targetSdkVersion 21
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:21.0.3'
    compile 'com.github.jjhesk:BringItBackAdvanceSlidingMenu:vX.XX'
}

Here is the error:
Error:(24, 13) Failed to resolve: com.github.jjhesk:BringItBackAdvanceSlidingMenu:vX.XX
Am I putting the dependency and repository lines in the right places?  If so, would like to request some insight into why it might be failing.  I'm using Android Studio 1.1.0

**Comment by jjhesk** [comment]
ok forget about using jitpack. Just using maven/jjhesk

**Comment by jitpack-io** [comment]
Hi,
Looks like `vX.XX` should be replaced with an actual version. Then it should work.
