### ISSUE TITLE
Support lower SDK version

### ISSUE THREAD

**Issue by kaiyan910** [jjhesk/BringItBackAdvanceSlidingMenu#18]
Hi, 

The library is great, but the only problem is that it only support SDK 17 or higher, can the library support lower version say 15 ? 

Currently I am overriding 

`<uses-sdk tools:overrideLibrary="com.hkm.slidingmenulib" />`

in order to use the library in SDK 15, is there any drawback?

Moreover, when I  use gradle to download the library it says `link_text_material_light` this color res is missing, any idea?

Thanks in advance

**Comment by MrBrightside29** [comment]
+1

**Comment by jjhesk** [comment]
this library is based on appcompact that is why. if you like to use for lower api please try the library from [jfeinistein](https://github.com/jfeinstein10/SlidingMenu)
