### ISSUE TITLE
Problem While Install Latest Version

### ISSUE THREAD

**Issue by rhonyabdullah** [jjhesk/BringItBackAdvanceSlidingMenu#23]
Hello, i'm getting this error while try to apply this library:
`Error:Failed to resolve: com.hkm.ui:ultimaterecyclerview:0.5.4`

Is there something wrong with my gradle ? Here's my gradle:
apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"

```
defaultConfig {
    applicationId "com.alfaonline.alfacart"
    minSdkVersion 14
    targetSdkVersion 23
    versionCode 1
    versionName "1.0"
}
buildTypes {
    release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
}
```

}

buildscript {
    repositories {
        maven { url 'https://jitpack.io' }
    }
}

repositories {
    mavenCentral()
    jcenter()
    maven { url "https://jitpack.io" }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.3.0'
    compile 'com.android.support:design:23.3.0'

```
//https://github.com/jjhesk/KickAssSlidingMenu
compile 'com.hkm.slidingmenulib:slidingmenulib:2.1.0'
```

}

**Comment by adryx92** [comment]
Same here.
For now, I had to revert back to  `compile 'com.hkm.slidingmenulib:slidingmenulib:2.0.3'`... 

BTW your minSdkVersion is too low: Android Studio says that the minimum required is 17 (because it's the one declared in the library). I think this should be better documented!

**Comment by erdem9011** [comment]
Same here. I wanted to use the transparent status bar feature. Unfortunately it seems it doesn't work in 2.0.3 version

**Comment by noura-rizk** [comment]
Hi did you find any solution for this, I had the same problem, and even with using the older version I still have other issues
