### ISSUE TITLE
outstanding issues

### ISSUE THREAD

**Issue by jjhesk** [jjhesk/BringItBackAdvanceSlidingMenu#3]
- [x] adjustment for navigation menu bar on screen also see the issue from [jeremyslidingmenu](https://github.com/jfeinstein10/SlidingMenu/issues/723) also see [stackoverflow](http://stackoverflow.com/questions/16092431/check-for-navigation-bar/23181183?noredirect=1#comment50374661_23181183) for more follow ups.
- [x] uncovered issues

**Comment by fbcbl** [comment]
How is the status on this issue?
